piston/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from .views import addurl, dropurl, manifest

urlpatterns = [
    url(r'^register', addurl, name='register'),
    url(r'^unregister', dropurl, name='unregister'),
    url(r'^manifest\.json', manifest, name='manifest'),
]

things/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from .views import (
	stuffindex, thing, AddThing, AddSchedule, 
	undones_json, finishjob_json, deletething_json, deleteschedule_json
	)

urlpatterns = [
    url('^thing$', stuffindex, name='index'),
    url(r'^thing/add$', AddThing.as_view(), name='addthing'),
    url(r'^thing/(\d+)$', thing, name='thing'),
    url(r'^thing/(\d+)/add$', AddSchedule.as_view(), name='addschedule'),
    url(r'^undones\.json', undones_json, name='undones.json'),
    url(r'^finish\.json', finishjob_json, name="finishjob.json"),
    url(r'^delete-thing\.json', deletething_json, name="delete-thing.json"),
    url(r'^delete-schedule\.json', deleteschedule_json, name="delete-schedule.json"),
]

upkeep/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from .views import frontpage
from django.contrib.auth.views import logout
from django.conf import settings
from django.forms import ModelForm

urlpatterns = []

if settings.DEBUG:
    from django.contrib import admin
    urlpatterns += [
        url(r'^!admin/', admin.site.urls),
    ]

urlpatterns += [
    url(r'^!csp/', include('cspreports.urls')),
    url(r'^!push/', include('piston.urls', namespace='push')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('things.urls', namespace='things')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^login/?', TemplateView.as_view(template_name="auth/login.html"), name='login'),
    url(r'^login/error', TemplateView.as_view(template_name="auth/login-error.html")),
    url(r'^login/inactive', TemplateView.as_view(template_name="auth/login-inactive.html")),
    url(r'^logout', logout, {'template_name': 'auth/logout.html'}, name='logout'),
    url(r'^$', frontpage),
]

things/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
import datetime

class ThingQuerySet(models.QuerySet):
    def accessible_by(self, user):
        if user.is_superuser:
            return self
        else:
            return self.filter(user=user)

class ThingManager(models.Manager):
    def get_queryset(self):
        return ThingQuerySet(self.model, using=self._db)

    def accessible_by(self, user):
        return self.get_queryset().accessible_by(user)

class Thing(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    class Meta:
        unique_together = ('user', 'name',)

    objects = ThingManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('things:thing', args=[self.id])


class ScheduleQuerySet(models.QuerySet):
    def accessible_by(self, user):
        if user.is_superuser:
            return self
        else:
            return self.filter(thing__user=user)

class ScheduleManager(models.Manager):
    def get_queryset(self):
        return ScheduleQuerySet(self.model, using=self._db)

    def accessible_by(self, user):
        return self.get_queryset().accessible_by(user)

class Schedule(models.Model):
    thing = models.ForeignKey(Thing, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    period = models.DurationField()
    next_job_at = models.DateField()

    class Meta:
        unique_together = ('thing', 'name',)

    objects = ScheduleManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('things:thing', args=[self.thing.id]) + '#schedule-{}'.format(self.id)

    def update_to_next(self, at=None):
        """
        Calculates the next job. Does not save.
        """
        if at is None:
            at = datetime.date.today()

        self.next_job_at = at + self.period


class JobQuerySet(models.QuerySet):
    def accessible_by(self, user):
        if user.is_superuser:
            return self
        else:
            return self.filter(schedule__thing__user=user)

class JobManager(models.Manager):
    def get_queryset(self):
        return ScheduleQuerySet(self.model, using=self._db)

    def accessible_by(self, user):
        return self.get_queryset().accessible_by(user)

class Job(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    when = models.DateField()
    done = models.BooleanField(default=False)
    # TODO: Only one undone job per schedule

    @property
    def name(self):
        return self.schedule.name

    objects = JobManager()

    def __str__(self):
        if self.done:
            return "{} at {} (done)".format(self.schedule, self.when)
        else:
            return "{} at {}".format(self.schedule, self.when)

templates/base.html
{% load staticfiles %}
{% load things %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="manifest" href="{% url 'push:manifest' %}">

        <link rel="stylesheet" href="{% static 'lib/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'lib/site.css' %}">
        <link rel="stylesheet" href="{% static 'common.css' %}">

        {% block head %}{% endblock %}
    </head>
    <body>
    {% get_things_for user as stuff %}
    {% if stuff != None %}
    <nav class="sidebar">
        <h1><a href="/">My Stuff</a></h1>
        {% if not stuff %}
        <p>You don't have any stuff!
        {% else %}
        <ul>
        {% for thing in stuff %}
        <li><a href="{{thing.get_absolute_url}}">{{thing}}</a></li>
        {% endfor %}
        </ul>
        {% endif %}
        <button data-action=show-dialog data-dialog=dlg-addthing><span class="fa fa-plus"></span> Add</button>

        <hr>

        <ul class="syslinks">
            <li><a href="/profile"><i class="fa fa-user"></i> Settings</a></li>
        </ul>

    </nav>
    {% endif %}
    <section>
    {% block content %}{% endblock %}
    </section>

    <dialog id="dlg-addthing">
        <button data-action=close><span class="fa fa-close"></span></button>
        <h3>Add Thing</h3>
        <form action="{% url 'things:addthing' %}" method=POST>
            {% csrf_token %}
            <p>I have a <input id="id_name" maxlength="128" name="name" type="text" placeholder="(noun)" required></p>
            <input type=submit value="Add">
        </form>
    </dialog>

    {% if DEBUG %}<a href="{% url 'logout' %}">Logout</a>{% endif %}
    <script src="{% static 'lib/doubledollar.js' %}"></script>
    {% if user.is_authenticated %}
    <script src="{% static 'lib/service-init.js' %}"></script>
    {% endif %}
    <script src="{% static 'common.js' %}"></script>
    {% block scripts %}{% endblock %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load profiles %}

{% block title %}Your Stuff{% endblock %}

{% block content %}
<h1>Your Stuff</h1>
<a href="{% url 'logout' %}">Logout</a>
{% endblock %}

templates/splash.html
{% extends "base.html" %}
{% load profiles %}

{% block title %}Upkeep: Maintainence Reminder{% endblock %}

{% block content %}
<p>I'll remind you when your stuff needs things.</p>

{% for be in backends.backends %}
<a class="loginbtn {{be}}" href="{% url "social:begin" be %}">{% socialname be %}</a>
{% endfor %}

{% endblock %}