piston/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from .views import addurl, dropurl, manifest

urlpatterns = [
    url(r'^register', addurl, name='register'),
    url(r'^unregister', dropurl, name='unregister'),
    url(r'^manifest\.json', manifest, name='manifest'),
]

things/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from .views import (
	stuffindex, thing, AddThing, AddSchedule, 
	undones_json, finishjob_json, deletething_json, deleteschedule_json
	)

urlpatterns = [
    url('^thing$', stuffindex, name='index'),
    url(r'^thing/add$', AddThing.as_view(), name='addthing'),
    url(r'^thing/(\d+)$', thing, name='thing'),
    url(r'^thing/(\d+)/add$', AddSchedule.as_view(), name='addschedule'),
    url(r'^undones\.json', undones_json, name='undones.json'),
    url(r'^finish\.json', finishjob_json, name="finishjob.json"),
    url(r'^delete-thing\.json', deletething_json, name="delete-thing.json"),
    url(r'^delete-schedule\.json', deleteschedule_json, name="delete-schedule.json"),
]

upkeep/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from .views import frontpage
from django.contrib.auth.views import logout
from django.conf import settings
from django.forms import ModelForm

urlpatterns = []

if settings.DEBUG:
    from django.contrib import admin
    urlpatterns += [
        url(r'^!admin/', admin.site.urls),
    ]

urlpatterns += [
    url(r'^!csp/', include('cspreports.urls')),
    url(r'^!push/', include('piston.urls', namespace='push')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('things.urls', namespace='things')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^login/?', TemplateView.as_view(template_name="auth/login.html"), name='login'),
    url(r'^login/error', TemplateView.as_view(template_name="auth/login-error.html")),
    url(r'^login/inactive', TemplateView.as_view(template_name="auth/login-inactive.html")),
    url(r'^logout', logout, {'template_name': 'auth/logout.html'}, name='logout'),
    url(r'^$', frontpage),
]

things/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
import datetime

class ThingQuerySet(models.QuerySet):
    def accessible_by(self, user):
        if user.is_superuser:
            return self
        else:
            return self.filter(user=user)

class ThingManager(models.Manager):
    def get_queryset(self):
        return ThingQuerySet(self.model, using=self._db)

    def accessible_by(self, user):
        return self.get_queryset().accessible_by(user)

class Thing(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    class Meta:
        unique_together = ('user', 'name',)

    objects = ThingManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('things:thing', args=[self.id])


class ScheduleQuerySet(models.QuerySet):
    def accessible_by(self, user):
        if user.is_superuser:
            return self
        else:
            return self.filter(thing__user=user)

class ScheduleManager(models.Manager):
    def get_queryset(self):
        return ScheduleQuerySet(self.model, using=self._db)

    def accessible_by(self, user):
        return self.get_queryset().accessible_by(user)

class Schedule(models.Model):
    thing = models.ForeignKey(Thing, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    period = models.DurationField()
    next_job_at = models.DateField()

    class Meta:
        unique_together = ('thing', 'name',)

    objects = ScheduleManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('things:thing', args=[self.thing.id]) + '#schedule-{}'.format(self.id)

    def update_to_next(self, at=None):
        """
        Calculates the next job. Does not save.
        """
        if at is None:
            at = datetime.date.today()

        self.next_job_at = at + self.period


class JobQuerySet(models.QuerySet):
    def accessible_by(self, user):
        if user.is_superuser:
            return self
        else:
            return self.filter(schedule__thing__user=user)

class JobManager(models.Manager):
    def get_queryset(self):
        return ScheduleQuerySet(self.model, using=self._db)

    def accessible_by(self, user):
        return self.get_queryset().accessible_by(user)

class Job(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    when = models.DateField()
    done = models.BooleanField(default=False)
    # TODO: Only one undone job per schedule

    @property
    def name(self):
        return self.schedule.name

    objects = JobManager()

    def __str__(self):
        if self.done:
            return "{} at {} (done)".format(self.schedule, self.when)
        else:
            return "{} at {}".format(self.schedule, self.when)

things/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from .models import Thing, Schedule, Job
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.forms import ModelForm
from django import forms
from django.http import JsonResponse
from django.db import transaction
import datetime
import json

def genctx(request, **vars):
    rv = {
        'forms': {
            'thing': ThingForm(),
            'schedule': ScheduleForm(),
        },
    }
    rv.update(vars)
    return rv

@login_required
def stuffindex(request):
    return render(request, "things/index.html", genctx(request,
        jobs=Job.objects.filter(schedule__thing__user=request.user, done=False),
    ))


@login_required
def thing(request, thingid):
    thing = get_object_or_404(Thing.objects.accessible_by(request.user), id=thingid)
    return render(request, 'things/thing.html', genctx(request,
            object=thing,
            undonejobs=Job.objects.filter(schedule__thing=thing, done=False),
        ))


class ThingForm(ModelForm):
    class Meta:
        model = Thing
        fields = ['name']

# Don't use CreateView because we have to do current user stuff
class AddThing(LoginRequiredMixin, FormView):
    template_name = 'things/addthing.html'
    form_class = ThingForm
    success_url = reverse_lazy("things:index")

    def form_valid(self, form):
        if form.is_valid():
            thing = form.save(commit=False)
            thing.user = self.request.user
            thing.save()
            self.success_url = thing.get_absolute_url()
        return super().form_valid(form)


class ScheduleForm(ModelForm):
    days = forms.IntegerField(min_value=1)
    class Meta:
        model = Schedule
        fields = ['name']

# Don't use CreateView because we have to do current user stuff
class AddSchedule(LoginRequiredMixin, FormView):
    template_name = 'things/addschedule.html'
    form_class = ScheduleForm
    success_url = reverse_lazy("things:index")

    def get_thing(self):
        return get_object_or_404(Thing.objects.accessible_by(self.request.user), id=self.args[0])

    def get_context_data(self, **kwargs):
        if 'thing' not in kwargs:
            kwargs['thing'] = self.get_thing()
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        if form.is_valid():
            sched = form.save(commit=False)
            sched.period = datetime.timedelta(days=form.cleaned_data['days'])
            sched.thing = self.get_thing()
            sched.next_job_at = datetime.date.today() + sched.period
            sched.save()
            self.success_url = sched.thing.get_absolute_url()
        return super().form_valid(form)

@login_required
def undones_json(request):
    ud = Job.objects.filter(schedule__thing__user=request.user, done=False)
    return JsonResponse({'jobs': [{
            'thing': {
                'name': j.schedule.thing.name,
                'id': j.schedule.thing.id,
                'url': j.schedule.thing.get_absolute_url(),
            },
            'schedule': {
                'name': j.schedule.name,
                'id': j.schedule.id,
                'url': j.schedule.get_absolute_url(),
            },
            'when': j.when.isoformat(),
        }
        for j in ud
        ]})

@login_required
def finishjob_json(request):
    if request.method != 'POST':
        return JsonResponse({'msg': 'Try a POST'}, status=405)  # Method Not Allowed
    obj = json.loads(request.body.decode('utf-8'))
    try:
        job = Job.objects.get(pk=obj['job'])
    except Job.DoesNotExist:
        return JsonResponse({'msg': 'Job does not exist'}, status=400)

    job.done = True
    job.schedule.update_to_next()

    with transaction.atomic():
        job.save()
        job.schedule.save()

    return JsonResponse({'ok': True})

@login_required
def deleteschedule_json(request):
    if request.method != 'POST':
        return JsonResponse({'msg': 'Try a POST'}, status=405)  # Method Not Allowed
    obj = json.loads(request.body.decode('utf-8'))
    try:
        schedule = Schedule.objects.get(pk=obj['schedule'])
    except Schedule.DoesNotExist:
        return JsonResponse({'msg': 'Schedule does not exist'}, status=400)

    schedule.delete()

    return JsonResponse({'ok': True})

@login_required
def deletething_json(request):
    if request.method != 'POST':
        return JsonResponse({'msg': 'Try a POST'}, status=405)  # Method Not Allowed
    obj = json.loads(request.body.decode('utf-8'))
    try:
        thing = Thing.objects.get(pk=obj['thing'])
    except Thing.DoesNotExist:
        return JsonResponse({'msg': 'Thing does not exist'}, status=400)

    thing.delete()

    return JsonResponse({'ok': True})

templates/things/addschedule.html
{% extends "base.html" %}
{% load profiles %}

{% block title %}Add a Schedule to {{thing}}{% endblock %}

{% block content %}
<h1>Add a Schedule to {{thing}}</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>

{% endblock %}

templates/things/addthing.html
{% extends "base.html" %}
{% load profiles %}

{% block title %}Add a Thing{% endblock %}

{% block content %}
<h1>Add a thing</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>

{% endblock %}

templates/things/index.html
{% extends "base.html" %}
{% load profiles %}
{% load static %}

{% block title %}Your Stuff{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'things/jobs.css' %}">
{% endblock %}
{% block scripts %}
<script src="{% static 'things/jobs.js' %}"></script>
{% endblock %}

{% block content %}

<h2>Undone Jobs</h2>

{% if not jobs %}
<p>You have nothing to do! Maybe buy a hammock?</p>
{% else %}
<ul>
{% for j in jobs %}
<li>
	{{j.schedule.name}}
	<button data-jobid="{{j.id}}" data-action="finish-job"><span class="fa fa-check"></span> Finish</button>
</li>
{% endfor %}
</ul>
{% endif %}


{% endblock %}

templates/things/thing.html
{% extends "base.html" %}
{% load profiles %}
{% load static %}

{% block title %}Your {{object}}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'things/jobs.css' %}">
{% endblock %}
{% block scripts %}
<script src="{% static 'things/jobs.js' %}"></script>
{% endblock %}

{% block content %}
<h1>
	{{object}}
	<button data-action=delete-thing data-thing="{{object.id}}" data-label="{{object.name}}"><span class="fa fa-trash"></span></button>
</h1>

<h2>Schedules</h2>
<ul>
{% for s in object.schedule_set.all %}
<li id="schedule-{{s.id}}">
	{{s}} every {{s.period.days}} days
	<button data-action=delete-schedule data-schedule="{{s.id}}" data-label="{{s.name}}"><span class="fa fa-trash"></span></button>
</li>
{% endfor %}
</ul>
<button data-action=show-dialog data-dialog=dlg-addschedule><span class="fa fa-plus"></span> Add</button>

<h2>Undone Jobs</h2>
<ul>
{% for j in undonejobs %}
<li>
    {{j.schedule.name}}
    <button data-jobid="{{j.id}}" data-action="finish-job"><span class="fa fa-check"></span> Finish</button>
</li>
{% endfor %}
</ul>

<dialog id="dlg-addschedule">
	<button data-action=close><span class="fa fa-close"></span></button>
	<h3>Add Schedule</h3>
    <form action="{% url 'things:addschedule' object.id %}" method=POST>
        {% csrf_token %}
        <p>I need to 
        	<input id="id_name" maxlength="128" name="name" type="text" placeholder="(verb)" required> 
        	every 
        	<input id="id_period" name="days" type="number" placeholder="(number)" min=1 step=1 required> 
        	days.</p>
	    <input type=submit value="Add">
    </form>
</dialog>

{% endblock %}